@baseURL=http://localhost:8000/api/v1/user
# @baseURL = https://portfolio.darshanv.website/api/v1/user

### Get all users
GET {{baseURL}}

### Create User
POST {{baseURL}}
Content-Type: application/json

{
    "name" : "Test test", 
    "email": "darshanv@gmail.com", 
    "password": "1234", 
    "username" : "testuser"
}

### Get User
GET {{baseURL}}/testuser

### Update User
PATCH {{baseURL}}/testuser
Content-Type: application/json

{
    
    "data" : {"password": "password"}
}

### Login user
POST {{baseURL}}/login
Content-Type: application/json

{ "data" : {
    "username": "testuser",
    "password": "1234"
}
}

### add social links
POST {{baseURL}}/social-links/testuser
Content-Type: application/json

{
    "data":[{"linkName":"Github","url":"https://github.com/DARSHAN-THE-CODER"},{"linkName":"linkedin","url":"http://linkedin.com"}]
}

### add about-cards
POST {{baseURL}}/about-cards/testuser
Content-Type: application/json

{
    "data": [{"title":"Photography", "description": "The most modern and high-quality design made at a professional level"}]
}

### add skills
POST {{baseURL}}/skills/testuser
Content-Type: application/json

{
    "data":[{"title":"C++","percentage":"76"}, {"title":"Python","percentage":"84"}]
}

### update social links
PATCH {{baseURL}}/social-links/3
Content-Type: application/json

{   "linkName": "linkedin 123",
    "url": "http://linkedin.com"
}

### update about-cards
PATCH {{baseURL}}/about-cards/3
Content-Type: application/json

{   "title": "Photography 123",
    "description": "The most modern and high-quality design made at a professional level"
}

### update skills
PATCH {{baseURL}}/skills/3
Content-Type: application/json

{   "title": "C++",
    "percentage": "96"
}

### delete user
DELETE {{baseURL}}/admin

### POST contact form
POST {{baseURL}}/form-response/darshanv
Content-Type: application/json

{
    "senderName": "xyz",
    "senderMail": "abc@gmail.com",
    "message": "Hello from xyz, Hello from xyz, Hello from xyz, Hello from xyz, Hello from xyz, Hello from xyz"
}

### get form responses
GET {{baseURL}}/form-response/darshanv

### delete form response
DELETE {{baseURL}}/form-response/darshanv

### hash all passwords
PATCH {{baseURL}}